# Generated by Django 3.0.6 on 2020-06-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0006_auto_20200605_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='account.Profile'),
        ),
    ]
