# Generated by Django 3.0.6 on 2020-06-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sales', '0002_sale_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='account.Profile'),
        ),
    ]
