# Generated by Django 3.0.6 on 2020-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200529_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.IntegerField()),
                ('type', models.CharField(choices=[('suplier', 'Supplier'), ('buyer', 'Buyer')], max_length=20)),
                ('product_group', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
