# Generated by Django 3.0.6 on 2020-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200529_1156'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='product_group',
            field=models.ManyToManyField(to='products.ProductGroup'),
        ),
    ]
